In [7]:
import pandas as pd

fusers = pd.read_csv("../data/fusers.csv")
users = pd.read_csv("../data/users.csv")

print(fusers.columns)
print(users.columns)

Index(['id', 'name', 'screen_name', 'fav_number', 'statuses_count',
       'followers_count', 'friends_count', 'favourites_count', 'listed_count',
       'created_at', 'url', 'lang', 'time_zone', 'location', 'default_profile',
       'default_profile_image', 'geo_enabled', 'profile_image_url',
       'profile_banner_url', 'profile_use_background_image',
       'profile_background_image_url_https', 'profile_text_color',
       'profile_image_url_https', 'profile_sidebar_border_color',
       'profile_background_tile', 'profile_sidebar_fill_color',
       'profile_background_image_url', 'profile_background_color',
       'profile_link_color', 'utc_offset', 'protected', 'verified',
       'description', 'updated', 'dataset'],
      dtype='object')
Index(['id', 'name', 'screen_name', 'fav_number', 'statuses_count',
       'followers_count', 'friends_count', 'favourites_count', 'listed_count',
       'created_at', 'url', 'lang', 'time_zone', 'location', 'default_profile',
       'default_profile_image', 'geo_enabled', 'profile_image_url',
       'profile_banner_url', 'profile_use_background_image',
       'profile_background_image_url_https', 'profile_text_color',
       'profile_image_url_https', 'profile_sidebar_border_color',
       'profile_background_tile', 'profile_sidebar_fill_color',
       'profile_background_image_url', 'profile_background_color',
       'profile_link_color', 'utc_offset', 'protected', 'verified',
       'description', 'updated', 'dataset'],
      dtype='object')

In [8]:
df = pd.concat([fusers, users], ignore_index=True)
df.head()

,id,name,screen_name,fav_number,statuses_count,followers_count,friends_count,favourites_count,listed_count,created_at,...,profile_sidebar_fill_color,profile_background_image_url,profile_background_color,profile_link_color,utc_offset,protected,verified,description,updated,dataset
0,370098498,pirfectmoses,pirfectmoses,1,24,4,588,16,0,Thu Sep 08 13:20:35 +0000 2011,...,DDEEF6,http://a0.twimg.com/profile_background_images/...,C6E2EE,1F98C7,NaN,NaN,NaN,NaN,2/14/2015 10:40,INT
1,37384589,SAK Nair,bsknair1967,898,656,57,693,597,0,Sun May 03 07:35:13 +0000 2009,...,DDEEF6,http://a0.twimg.com/images/themes/theme1/bg.png,C0DEED,0084B4,NaN,NaN,NaN,in Kuwait with my buetiful family.,2/14/2015 10:40,INT
2,72110028,Deepak,dedjven,4507,1234,15,104,1150,0,Sun Sep 06 19:50:08 +0000 2009,...,EFEFEF,http://a0.twimg.com/images/themes/theme14/bg.gif,131516,9999,-39600.0,NaN,NaN,NaN,2/14/2015 10:40,INT
3,82885728,Marcos Vinicius,BrowAlves,0,573,14,227,530,0,Fri Oct 16 14:02:48 +0000 2009,...,DDEEF6,http://a0.twimg.com/profile_background_images/...,C0DEED,0084B4,NaN,NaN,NaN,NaN,2/14/2015 10:40,INT
4,110120789,Shri Kant Kanaujia,kanaujiask,2321,675,18,519,653,0,Sun Jan 31 12:08:41 +0000 2010,...,DDEEF6,http://a0.twimg.com/images/themes/theme1/bg.png,C0DEED,0084B4,19800.0,NaN,NaN,NaN,2/14/2015 10:40,INT

In [9]:
df['dataset'].unique()

array(['INT', 'E13'], dtype=object)

In [10]:
df = pd.concat([fusers, users], ignore_index=True)
df['dataset'].unique()

array(['INT', 'E13'], dtype=object)

In [11]:
df['dataset'].unique()

array(['INT', 'E13'], dtype=object)

In [12]:
df['dataset'].value_counts()

dataset
E13    1481
INT    1337
Name: count, dtype: int64

In [13]:
df['dataset'].value_counts()

dataset
E13    1481
INT    1337
Name: count, dtype: int64

In [14]:
df[df['dataset'] == 'INT'].head()
df[df['dataset'] == 'E13'].head()

,id,name,screen_name,fav_number,statuses_count,followers_count,friends_count,favourites_count,listed_count,created_at,...,profile_sidebar_fill_color,profile_background_image_url,profile_background_color,profile_link_color,utc_offset,protected,verified,description,updated,dataset
1337,3610511,Davide Dellacasa,braddd,0,20370,5470,2385,145,52,Fri Apr 06 10:58:22 +0000 2007,...,FFF7CC,http://a0.twimg.com/profile_background_images/...,BADFCD,FF0000,3600.0,NaN,NaN,Founder of http://www.screenweek.it & http://w...,2/14/2015 10:54,E13
1338,5656162,Simone Economo,eKoeS,68,3131,506,381,9,40,Mon Apr 30 15:08:42 +0000 2007,...,DDEEF6,http://a0.twimg.com/images/themes/theme1/bg.png,C0DEED,0084B4,3600.0,NaN,NaN,BSc degree (cum laude) in Computer Engineering...,2/14/2015 10:54,E13
1339,5682702,tacone,tacone_,7696,4024,264,87,323,16,Tue May 01 11:53:40 +0000 2007,...,0,http://a0.twimg.com/profile_background_images/...,1A1B1F,2FC2EF,3600.0,NaN,NaN,Cogito ergo bestemmio.,2/14/2015 10:54,E13
1340,6067292,alesaura,alesstar,202,40586,640,622,1118,32,Tue May 15 16:55:16 +0000 2007,...,95E8EC,http://a0.twimg.com/images/themes/theme4/bg.gif,0099B9,0099B9,3600.0,NaN,NaN,"Se la vita ti dà sarde, scapocciale!",2/14/2015 10:54,E13
1341,6015122,Angelo,PerDiletto,37318,2016,62,64,13,0,Sun May 13 19:52:00 +0000 2007,...,F6F6F6,http://a0.twimg.com/images/themes/theme18/bg.gif,ACDED6,38543,3600.0,NaN,NaN,Je me souviens,2/14/2015 10:54,E13

In [37]:
df[df['dataset'] == 'INT'].head()

,id,name,screen_name,fav_number,statuses_count,followers_count,friends_count,favourites_count,listed_count,created_at,...,profile_background_image_url,profile_background_color,profile_link_color,utc_offset,protected,verified,description,updated,dataset,label
0,370098498,pirfectmoses,pirfectmoses,1,24,4,588,16,0,Thu Sep 08 13:20:35 +0000 2011,...,http://a0.twimg.com/profile_background_images/...,C6E2EE,1F98C7,NaN,NaN,NaN,NaN,2/14/2015 10:40,INT,0
1,37384589,SAK Nair,bsknair1967,898,656,57,693,597,0,Sun May 03 07:35:13 +0000 2009,...,http://a0.twimg.com/images/themes/theme1/bg.png,C0DEED,0084B4,NaN,NaN,NaN,in Kuwait with my buetiful family.,2/14/2015 10:40,INT,0
2,72110028,Deepak,dedjven,4507,1234,15,104,1150,0,Sun Sep 06 19:50:08 +0000 2009,...,http://a0.twimg.com/images/themes/theme14/bg.gif,131516,9999,-39600.0,NaN,NaN,NaN,2/14/2015 10:40,INT,0
3,82885728,Marcos Vinicius,BrowAlves,0,573,14,227,530,0,Fri Oct 16 14:02:48 +0000 2009,...,http://a0.twimg.com/profile_background_images/...,C0DEED,0084B4,NaN,NaN,NaN,NaN,2/14/2015 10:40,INT,0
4,110120789,Shri Kant Kanaujia,kanaujiask,2321,675,18,519,653,0,Sun Jan 31 12:08:41 +0000 2010,...,http://a0.twimg.com/images/themes/theme1/bg.png,C0DEED,0084B4,19800.0,NaN,NaN,NaN,2/14/2015 10:40,INT,0

In [16]:
df['label'] = df['dataset'].apply(lambda x: 0 if x == 'INT' else 1)

In [17]:
df_clean = df.copy()

columns_to_drop = [
    'id', 'name', 'screen_name', 'url', 'profile_image_url', 'profile_banner_url',
    'profile_background_image_url', 'profile_background_image_url_https',
    'profile_image_url_https', 'description', 'location', 'time_zone',
    'profile_sidebar_border_color', 'profile_sidebar_fill_color', 'profile_text_color',
    'profile_background_color', 'profile_link_color', 'created_at', 'updated',
    'dataset'
]

df_clean = df_clean.drop(columns=columns_to_drop)
df_clean.head()

,fav_number,statuses_count,followers_count,friends_count,favourites_count,listed_count,lang,default_profile,default_profile_image,geo_enabled,profile_use_background_image,profile_background_tile,utc_offset,protected,verified,label
0,1,24,4,588,16,0,en,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,0
1,898,656,57,693,597,0,en,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,0
2,4507,1234,15,104,1150,0,en,NaN,NaN,1.0,1.0,1.0,-39600.0,NaN,NaN,0
3,0,573,14,227,530,0,en,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,0
4,2321,675,18,519,653,0,en,1.0,1.0,NaN,1.0,NaN,19800.0,NaN,NaN,0

In [20]:
bool_cols = [
    'default_profile', 'default_profile_image', 'geo_enabled',
    'profile_use_background_image', 'profile_background_tile',
    'protected', 'verified'
]

for col in bool_cols:
    df_clean[col] = df_clean[col].fillna(False).astype(int)

df_clean.head()

,fav_number,statuses_count,followers_count,friends_count,favourites_count,listed_count,lang,default_profile,default_profile_image,geo_enabled,profile_use_background_image,profile_background_tile,utc_offset,protected,verified,label
0,1,24,4,588,16,0,en,0,0,0,1,0,NaN,0,0,0
1,898,656,57,693,597,0,en,1,0,0,1,0,NaN,0,0,0
2,4507,1234,15,104,1150,0,en,0,0,1,1,1,-39600.0,0,0,0
3,0,573,14,227,530,0,en,0,0,0,1,0,NaN,0,0,0
4,2321,675,18,519,653,0,en,1,1,0,1,0,19800.0,0,0,0

In [19]:
import warnings
warnings.filterwarnings('ignore')

In [21]:
df_clean.head()

,fav_number,statuses_count,followers_count,friends_count,favourites_count,listed_count,lang,default_profile,default_profile_image,geo_enabled,profile_use_background_image,profile_background_tile,utc_offset,protected,verified,label
0,1,24,4,588,16,0,en,0,0,0,1,0,NaN,0,0,0
1,898,656,57,693,597,0,en,1,0,0,1,0,NaN,0,0,0
2,4507,1234,15,104,1150,0,en,0,0,1,1,1,-39600.0,0,0,0
3,0,573,14,227,530,0,en,0,0,0,1,0,NaN,0,0,0
4,2321,675,18,519,653,0,en,1,1,0,1,0,19800.0,0,0,0

In [22]:
# Followers–Friends Ratio
df_clean['ff_ratio'] = df_clean['followers_count'] / (df_clean['friends_count'] + 1)

# Activity Score
df_clean['activity_score'] = df_clean['statuses_count'] / (df_clean['friends_count'] + 1)

# Engagement Score
df_clean['engagement_score'] = df_clean['favourites_count'] / (df_clean['followers_count'] + 1)

In [23]:
df_fe = df_clean.copy()
df_fe.head()

,fav_number,statuses_count,followers_count,friends_count,favourites_count,listed_count,lang,default_profile,default_profile_image,geo_enabled,profile_use_background_image,profile_background_tile,utc_offset,protected,verified,label,ff_ratio,activity_score,engagement_score
0,1,24,4,588,16,0,en,0,0,0,1,0,NaN,0,0,0,0.006791,0.040747,3.200000
1,898,656,57,693,597,0,en,1,0,0,1,0,NaN,0,0,0,0.082133,0.945245,10.293103
2,4507,1234,15,104,1150,0,en,0,0,1,1,1,-39600.0,0,0,0,0.142857,11.752381,71.875000
3,0,573,14,227,530,0,en,0,0,0,1,0,NaN,0,0,0,0.061404,2.513158,35.333333
4,2321,675,18,519,653,0,en,1,1,0,1,0,19800.0,0,0,0,0.034615,1.298077,34.368421

In [24]:
df_clean.columns

Index(['fav_number', 'statuses_count', 'followers_count', 'friends_count',
       'favourites_count', 'listed_count', 'lang', 'default_profile',
       'default_profile_image', 'geo_enabled', 'profile_use_background_image',
       'profile_background_tile', 'utc_offset', 'protected', 'verified',
       'label', 'ff_ratio', 'activity_score', 'engagement_score'],
      dtype='object')

In [25]:
df.columns

Index(['id', 'name', 'screen_name', 'fav_number', 'statuses_count',
       'followers_count', 'friends_count', 'favourites_count', 'listed_count',
       'created_at', 'url', 'lang', 'time_zone', 'location', 'default_profile',
       'default_profile_image', 'geo_enabled', 'profile_image_url',
       'profile_banner_url', 'profile_use_background_image',
       'profile_background_image_url_https', 'profile_text_color',
       'profile_image_url_https', 'profile_sidebar_border_color',
       'profile_background_tile', 'profile_sidebar_fill_color',
       'profile_background_image_url', 'profile_background_color',
       'profile_link_color', 'utc_offset', 'protected', 'verified',
       'description', 'updated', 'dataset', 'label'],
      dtype='object')

In [26]:
df['label'] = df['dataset'].apply(lambda x: 0 if x == 'INT' else 1)

In [27]:
df_clean['label'] = df['label']

In [28]:
df_fe = df_clean.copy()

In [29]:
df_fe.columns

Index(['fav_number', 'statuses_count', 'followers_count', 'friends_count',
       'favourites_count', 'listed_count', 'lang', 'default_profile',
       'default_profile_image', 'geo_enabled', 'profile_use_background_image',
       'profile_background_tile', 'utc_offset', 'protected', 'verified',
       'label', 'ff_ratio', 'activity_score', 'engagement_score'],
      dtype='object')

In [30]:
features = [
    'followers_count',
    'friends_count',
    'verified',
    'default_profile',
    'ff_ratio'
]

X = df_fe[features]
y = df_fe['label']

X.shape, y.shape

((2818, 5), (2818,))

In [31]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [36]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

rf = RandomForestClassifier(n_estimators=200, random_state=42)
rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)

print("Random Forest")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))

Random Forest
Accuracy: 0.9911347517730497
Precision: 0.9965870307167235
Recall: 0.9864864864864865
F1 Score: 0.9915110356536503

In [35]:
import pickle

with open("../models/fake_profile_model.pkl", "wb") as f:
    pickle.dump(rf, f)

print("5-feature model saved successfully")

5-feature model saved successfully